#jdbc
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acl
    username: aclij
    password: 1c1155hg
  jpa:
    show_sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
# user service customize

server:
  error:
    whitelabel:
      enabled : false
  servlet:
    session:
      timeout: 60m
unique-id:
  length: 6
  characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

user:
  service:
    default_role: ROLE_USER

logging:
  level:
    web: debug

jwt:
  secret: XcESicxsXBIoIgR+aYcDtn9YGWIIOsH8E892Pce8dGc
  lifetime: 30m

chess:
  websocket:
    response_url: /topic/response/chess/
  controller:
    end_point : /chess/

